import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:digital_prescription/models/medicine.dart';

class DatabaseHelper {
  static final DatabaseHelper _instance = DatabaseHelper._internal();
  factory DatabaseHelper() => _instance;
  DatabaseHelper._internal();

  static Database? _database;

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initDatabase();
    return _database!;
  }

  Future<Database> _initDatabase() async {
    String path = join(await getDatabasesPath(), 'medicines.db');
    return await openDatabase(path, version: 1, onCreate: _onCreate);
  }

  Future<void> _onCreate(Database db, int version) async {
    await db.execute('''
      CREATE TABLE medicines(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL
      )
    ''');
    await _seedDatabase(db);
  }

  Future<List<Medicine>> getMedicines({int limit = 20}) async {
    final db = await database;
    final List<Map<String, dynamic>> maps = await db.query(
      'medicines',
      limit: limit,
    );
    return List.generate(maps.length, (i) {
      return Medicine.fromMap(maps[i]);
    });
  }

  Future<List<Medicine>> getAllMedicines() async {
    final db = await database;
    final List<Map<String, dynamic>> maps = await db.query('medicines');
    return List.generate(maps.length, (i) {
      return Medicine.fromMap(maps[i]);
    });
  }

  Future<void> deleteMedicine(int id) async {
    final db = await database;
    await db.delete('medicines', where: 'id = ?', whereArgs: [id]);
  }

  Future<void> insertMedicine(Medicine medicine) async {
    final db = await database;
    await db.insert(
      'medicines',
      medicine.toMap(),
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  Future<void> _seedDatabase(Database db) async {
    List<String> initialMedicines = [
      'Napa',
      'Paracetamol',
      'Ace',
      'Omeprazole',
      'Seclo',
      'Fexo',
      'Rupa',
      'Ciprofloxacin',
      'Azithromycin',
      'Metronidazole',
      'Amoxicillin',
      'Doxycycline',
      'Cetirizine',
      'Loratadine',
      'Desloratadine',
      'Montelukast',
      'Salbutamol',
      'Budesonide',
      'Fluticasone',
      'Ibuprofen',
      'Ketorolac',
      'Diclofenac',
      'Naproxen',
      'Aspirin',
      'Clopidogrel',
      'Atorvastatin',
      'Rosuvastatin',
      'Simvastatin',
      'Metformin',
      'Gliclazide',
      'Insulin',
      'Amlodipine',
      'Losartan',
      'Telmisartan',
      'Olmesartan',
      'Bisoprolol',
      'Carvedilol',
      'Metoprolol',
      'Propranolol',
      'Furosemide',
      'Spironolactone',
      'Hydrochlorothiazide',
      'Ramipril',
      'Enalapril',
      'Lisinopril',
      'Captopril',
      'Ranitidine',
      'Famotidine',
      'Pantoprazole',
      'Esomeprazole',
      'Lansoprazole',
      'Domperidone',
      'Ondansetron',
      'Hyoscine',
      'Tiemonium',
      'Albendazole',
      'Mebendazole',
      'Fluconazole',
      'Miconazole',
      'Clotrimazole',
      'Terbinafine',
      'Griseofulvin',
      'Nystatin',
      'Amphotericin B',
      'Gentamicin',
      'Neomycin',
      'Tobramycin',
      'Ofloxacin',
      'Levofloxacin',
      'Moxifloxacin',
      'Gatifloxacin',
      'Cefixime',
      'Cefuroxime',
      'Cefpodoxime',
      'Ceftriaxone',
      'Cefepime',
      'Meropenem',
      'Imipenem',
      'Vancomycin',
      'Linezolid',
      'Tigecycline',
      'Colistin',
      'Polymyxin B',
      'Bacitracin',
      'Mupirocin',
      'Fusidic acid',
      'Silver sulfadiazine',
      'Povidone-iodine',
      'Chlorhexidine',
      'Hydrogen peroxide',
      'Alcohol',
      'Benzoyl peroxide',
      'Adapalene',
      'Tretinoin',
      'Isotretinoin',
      'Hydrocortisone',
      'Betamethasone',
      'Clobetasol',
      'Mometasone',
      'Triamcinolone',
      'Tacrolimus',
      'Pimecrolimus',
      'Calcipotriol',
      'Methotrexate',
      'Cyclosporine',
      'Azathioprine',
      'Mycophenolate',
      'Hydroxychloroquine',
      'Sulfasalazine',
      'Leflunomide',
      'Etanercept',
      'Adalimumab',
      'Infliximab',
      'Rituximab',
      'Tocilizumab',
      'Abatacept',
      'Ustekinumab',
      'Secukinumab',
      'Ixekizumab',
      'Brodalumab',
      'Guselkumab',
      'Risankizumab',
      'Tildrakizumab',
      'Certolizumab',
      'Golimumab',
      'Anakinra',
      'Canakinumab',
      'Rilonacept',
      'Belimumab',
      'Allopurinol',
      'Febuxostat',
      'Probenecid',
      'Colchicine',
      'Indomethacin',
      'Prednisone',
      'Methylprednisolone',
      'Dexamethasone',
      'Codeine',
      'Tramadol',
      'Morphine',
      'Fentanyl',
      'Oxycodone',
      'Hydromorphone',
      'Buprenorphine',
      'Naloxone',
      'Gabapentin',
      'Pregabalin',
      'Amitriptyline',
      'Nortriptyline',
      'Duloxetine',
      'Venlafaxine',
      'Sertraline',
      'Fluoxetine',
      'Paroxetine',
      'Citalopram',
      'Escitalopram',
      'Fluvoxamine',
      'Mirtazapine',
      'Trazodone',
      'Bupropion',
      'Buspirone',
      'Alprazolam',
      'Clonazepam',
      'Diazepam',
      'Lorazepam',
      'Midazolam',
      'Zolpidem',
      'Zopiclone',
      'Eszopiclone',
      'Melatonin',
      'Ramelteon',
      'Tasimelteon',
      'Suvorexant',
      'Lemborexant',
      'Phenobarbital',
      'Primidone',
      'Phenytoin',
      'Carbamazepine',
      'Oxcarbazepine',
      'Valproic acid',
      'Lamotrigine',
      'Topiramate',
      'Levetiracetam',
      'Brivaracetam',
      'Lacosamide',
      'Zonisamide',
      'Ethosuximide',
      'Vigabatrin',
      'Tiagabine',
      'Felbamate',
      'Rufinamide',
      'Clobazam',
      'Stiripentol',
      'Cannabidiol',
      'Haloperidol',
      'Chlorpromazine',
      'Fluphenazine',
      'Thioridazine',
      'Perphenazine',
      'Trifluoperazine',
      'Risperidone',
      'Olanzapine',
      'Quetiapine',
      'Aripiprazole',
      'Ziprasidone',
      'Paliperidone',
      'Iloperidone',
      'Asenapine',
      'Lurasidone',
      'Cariprazine',
      'Brexpiprazole',
      'Clozapine',
      'Lithium',
      'Donepezil',
      'Rivastigmine',
      'Galantamine',
      'Memantine',
      'Levodopa',
      'Carbidopa',
      'Entacapone',
      'Tolcapone',
      'Selegiline',
      'Rasagiline',
      'Safinamide',
      'Pramipexole',
      'Ropinirole',
      'Rotigotine',
      'Apomorphine',
      'Amantadine',
      'Trihexyphenidyl',
      'Benztropine',
      'Biperiden',
      'Procyclidine',
      'Sumatriptan',
      'Rizatriptan',
      'Zolmitriptan',
      'Naratriptan',
      'Almotriptan',
      'Eletriptan',
      'Frovatriptan',
      'Ergotamine',
      'Dihydroergotamine',
      'Caffeine',
      'Prochlorperazine',
      'Metoclopramide',
      'Promethazine',
      'Dimenhydrinate',
      'Meclizine',
      'Scopolamine',
      'Aprepitant',
      'Fosaprepitant',
      'Netupitant',
      'Palonosetron',
      'Granisetron',
      'Dolasetron',
      'Tropisetron',
      'Loperamide',
      'Diphenoxylate',
      'Atropine',
      'Bismuth subsalicylate',
      'Kaolin',
      'Pectin',
      'Lactulose',
      'Polyethylene glycol',
      'Magnesium hydroxide',
      'Bisacodyl',
      'Senna',
      'Docusate',
      'Glycerin',
      'Sildenafil',
      'Tadalafil',
      'Vardenafil',
      'Avanafil',
      'Alprostadil',
      'Tamsulosin',
      'Alfuzosin',
      'Doxazosin',
      'Terazosin',
      'Silodosin',
      'Finasteride',
      'Dutasteride',
      'Oxybutynin',
      'Tolterodine',
      'Solifenacin',
      'Darifenacin',
      'Fesoterodine',
      'Trospium',
      'Mirabegron',
      'Vibegron',
      'Desmopressin',
      'Imipramine',
      'Warfarin',
      'Rivaroxaban',
      'Apixaban',
      'Edoxaban',
      'Dabigatran',
      'Heparin',
      'Enoxaparin',
      'Dalteparin',
      'Tinzaparin',
      'Fondaparinux',
      'Argatroban',
      'Bivalirudin',
      'Lepirudin',
      'Desirudin',
      'Danaparoid',
      'Protamine',
      'Vitamin K',
      'Idarucizumab',
      'Andexanet alfa',
      'Ciraparantag',
      'Tranexamic acid',
      'Aminocaproic acid',
      'Aprotinin',
      'Epsilon-aminocaproic acid',
      'Factor VIIa',
      'Factor VIII',
      'Factor IX',
      'Factor XIII',
      'Fibrinogen',
      'Prothrombin complex concentrate',
      'Anti-inhibitor coagulant complex',
      'Eltrombopag',
      'Romiplostim',
      'Avatrombopag',
      'Lusutrombopag',
      'Fostamatinib',
      'Caplacizumab',
      'Eculizumab',
      'Ravulizumab',
      'Pegcetacoplan',
      'Sutimlimab',
      'Icatibant',
      'Lanadelumab',
      'Berotralstat',
      'C1 esterase inhibitor',
      'Cinryze',
      'Haegarda',
      'Ruconest',
      'Berinert',
      'Kallikrein inhibitor',
      'Ecallantide',
      'Plasma-derived C1-INH',
      'Recombinant C1-INH',
      'Bradykinin B2 receptor antagonist',
      'Oral plasma kallikrein inhibitor',
      'Hereditary angioedema',
      'HAE',
      'Hereditary angioedema with C1-inhibitor deficiency',
      'HAE type 1',
      'HAE type 2',
      'Hereditary angioedema with normal C1-inhibitor',
      'nC1-INH-HAE',
      'HAE with factor XII mutation',
      'FXII-HAE',
      'HAE with angiopoietin-1 mutation',
      'ANGPT1-HAE',
      'HAE with plasminogen mutation',
      'PLG-HAE',
      'HAE of unknown origin',
      'U-HAE',
      'Acquired angioedema',
      'AAE',
      'Acquired angioedema with C1-inhibitor deficiency',
      'C1-INH-AAE',
      'Acquired angioedema with normal C1-inhibitor',
      'nC1-INH-AAE',
      'Idiopathic angioedema',
      'IAE',
      'Histaminergic idiopathic angioedema',
      'H-IAE',
      'Non-histaminergic idiopathic angioedema',
      'nH-IAE',
      'ACE inhibitor-induced angioedema',
      'ACEI-AAE',
      'Angiotensin receptor blocker-induced angioedema',
      'ARB-AAE',
      'NSAID-induced angioedema',
      'NSAID-AAE',
      'Allergic angioedema',
      'Pseudoallergic angioedema',
      'Anaphylaxis',
      'Urticaria',
      'Chronic urticaria',
      'Acute urticaria',
      'Chronic spontaneous urticaria',
      'CSU',
      'Chronic inducible urticaria',
      'CIndU',
      'Symptomatic dermographism',
      'Cold urticaria',
      'Delayed pressure urticaria',
      'Solar urticaria',
      'Heat urticaria',
      'Vibratory urticaria',
      'Aquagenic urticaria',
      'Cholinergic urticaria',
      'Contact urticaria',
      'Adrenergic urticaria',
      'Exercise-induced anaphylaxis',
      'Food-dependent exercise-induced anaphylaxis',
      'FDEIA',
      'Mastocytosis',
      'Systemic mastocytosis',
      'Cutaneous mastocytosis',
      'Mast cell activation syndrome',
      'MCAS',
      'Eosinophilic esophagitis',
      'EoE',
      'Atopic dermatitis',
      'Eczema',
      'Psoriasis',
      'Psoriatic arthritis',
      'Rheumatoid arthritis',
      'Systemic lupus erythematosus',
      'SLE',
      'Sjogren\'s syndrome',
      'Scleroderma',
      'Systemic sclerosis',
      'Polymyositis',
      'Dermatomyositis',
      'Mixed connective tissue disease',
      'MCTD',
      'Undifferentiated connective tissue disease',
      'UCTD',
      'Antiphospholipid syndrome',
      'APS',
      'Vasculitis',
      'Giant cell arteritis',
      'Takayasu\'s arteritis',
      'Polyarteritis nodosa',
      'Kawasaki disease',
      'Granulomatosis with polyangiitis',
      'GPA',
      'Wegener\'s granulomatosis',
      'Microscopic polyangiitis',
      'MPA',
      'Eosinophilic granulomatosis with polyangiitis',
      'EGPA',
      'Churg-Strauss syndrome',
      'IgA vasculitis',
      'Henoch-Schonlein purpura',
      'Cryoglobulinemic vasculitis',
      'Behcet\'s disease',
      'Cogan\'s syndrome',
      'Primary angiitis of the CNS',
      'PACNS',
      'Thromboangiitis obliterans',
      'Buerger\'s disease',
      'Sarcoidosis',
      'Amyloidosis',
      'Familial Mediterranean fever',
      'FMF',
      'Tumor necrosis factor receptor-associated periodic syndrome',
      'TRAPS',
      'Hyperimmunoglobulinemia D syndrome',
      'HIDS',
      'Mevalonate kinase deficiency',
      'MKD',
      'Cryopyrin-associated periodic syndromes',
      'CAPS',
      'Familial cold autoinflammatory syndrome',
      'FCAS',
      'Muckle-Wells syndrome',
      'MWS',
      'Neonatal-onset multisystem inflammatory disease',
      'NOMID',
      'Chronic infantile neurologic, cutaneous, and articular syndrome',
      'CINCA',
      'Blau syndrome',
      'Pyogenic arthritis, pyoderma gangrenosum, and acne syndrome',
      'PAPA',
      'Deficiency of the interleukin-1 receptor antagonist',
      'DIRA',
      'Cardiovascular disease',
      'Hypertension',
      'Coronary artery disease',
      'Myocardial infarction',
      'Heart failure',
      'Arrhythmia',
      'Stroke',
      'Peripheral artery disease',
      'Venous thromboembolism',
      'Pulmonary embolism',
      'Deep vein thrombosis',
      'Diabetes mellitus',
      'Type 1 diabetes',
      'Type 2 diabetes',
      'Gestational diabetes',
      'Thyroid disease',
      'Hypothyroidism',
      'Hyperthyroidism',
      'Thyroiditis',
      'Goiter',
      'Thyroid nodules',
      'Thyroid cancer',
      'Adrenal disorders',
      'Cushing\'s syndrome',
      'Addison\'s disease',
      'Congenital adrenal hyperplasia',
      'Pheochromocytoma',
      'Hyperaldosteronism',
      'Pituitary disorders',
      'Acromegaly',
      'Gigantism',
      'Dwarfism',
      'Hypopituitarism',
      'Diabetes insipidus',
      'SIADH',
      'Prolactinoma',
      'Growth hormone deficiency',
      'Parathyroid disorders',
      'Hyperparathyroidism',
      'Hypoparathyroidism',
      'Bone disorders',
      'Osteoporosis',
      'Osteomalacia',
      'Rickets',
      'Paget\'s disease of bone',
      'Osteogenesis imperfecta',
      'Renal disease',
      'Chronic kidney disease',
      'Acute kidney injury',
      'Glomerulonephritis',
      'Nephrotic syndrome',
      'Polycystic kidney disease',
      'Kidney stones',
      'Urinary tract infection',
      'Gastrointestinal disorders',
      'Gastroesophageal reflux disease',
      'GERD',
      'Peptic ulcer disease',
      'Gastritis',
      'Helicobacter pylori infection',
      'Celiac disease',
      'Inflammatory bowel disease',
      'Crohn\'s disease',
      'Ulcerative colitis',
      'Irritable bowel syndrome',
      'IBS',
      'Diverticulitis',
      'Hemorrhoids',
      'Anal fissure',
      'Constipation',
      'Diarrhea',
      'Liver disease',
      'Hepatitis',
      'Hepatitis A',
      'Hepatitis B',
      'Hepatitis C',
      'Hepatitis D',
      'Hepatitis E',
      'Autoimmune hepatitis',
      'Alcoholic liver disease',
      'Non-alcoholic fatty liver disease',
      'NAFLD',
      'Non-alcoholic steatohepatitis',
      'NASH',
      'Cirrhosis',
      'Liver failure',
      'Liver cancer',
      'Pancreatitis',
      'Gallstones',
      'Cholecystitis',
      'Cholangitis',
      'Biliary colic',
      'Respiratory diseases',
      'Asthma',
      'Chronic obstructive pulmonary disease',
      'COPD',
      'Bronchitis',
      'Emphysema',
      'Pneumonia',
      'Tuberculosis',
      'Lung cancer',
      'Cystic fibrosis',
      'Pulmonary fibrosis',
      'Sleep apnea',
      'Neurological disorders',
      'Epilepsy',
      'Seizures',
      'Alzheimer\'s disease',
      'Parkinson\'s disease',
      'Multiple sclerosis',
      'Amyotrophic lateral sclerosis',
      'ALS',
      'Huntington\'s disease',
      'Migraine',
      'Headache',
      'Dementia',
      'Meningitis',
      'Encephalitis',
      'Brain tumor',
      'Spinal cord injury',
      'Peripheral neuropathy',
      'Guillain-Barre syndrome',
      'Myasthenia gravis',
      'Muscular dystrophy',
      'Cerebral palsy',
      'Mental health disorders',
      'Depression',
      'Anxiety',
      'Bipolar disorder',
      'Schizophrenia',
      'Obsessive-compulsive disorder',
      'OCD',
      'Post-traumatic stress disorder',
      'PTSD',
      'Panic disorder',
      'Phobias',
      'Eating disorders',
      'Anorexia nervosa',
      'Bulimia nervosa',
      'Binge eating disorder',
      'Substance use disorders',
      'Alcohol use disorder',
      'Opioid use disorder',
      'Tobacco use disorder',
      'Attention-deficit/hyperactivity disorder',
      'ADHD',
      'Autism spectrum disorder',
      'ASD',
      'Infectious diseases',
      'HIV/AIDS',
      'Influenza',
      'Common cold',
      'Measles',
      'Mumps',
      'Rubella',
      'Chickenpox',
      'Shingles',
      'Herpes',
      'Human papillomavirus',
      'HPV',
      'Syphilis',
      'Gonorrhea',
      'Chlamydia',
      'Trichomoniasis',
      'Malaria',
      'Dengue',
      'Zika',
      'Chikungunya',
      'Yellow fever',
      'Ebola',
      'COVID-19',
      'Cancer',
      'Breast cancer',
      'Lung cancer',
      'Prostate cancer',
      'Colorectal cancer',
      'Skin cancer',
      'Melanoma',
      'Leukemia',
      'Lymphoma',
      'Ovarian cancer',
      'Cervical cancer',
      'Uterine cancer',
      'Bladder cancer',
      'Kidney cancer',
      'Pancreatic cancer',
      'Stomach cancer',
      'Esophageal cancer',
      'Head and neck cancer',
      'Brain cancer',
      'Bone cancer',
      'Sarcoma',
      'Thyroid cancer',
      'Testicular cancer',
      'Hodgkin lymphoma',
      'Non-Hodgkin lymphoma',
      'Multiple myeloma',
      'Myelodysplastic syndromes',
      'MDS',
      'Myeloproliferative neoplasms',
      'MPN',
      'Polycythemia vera',
      'Essential thrombocythemia',
      'Primary myelofibrosis',
      'Chronic myeloid leukemia',
      'CML',
      'Acute myeloid leukemia',
      'AML',
      'Chronic lymphocytic leukemia',
      'CLL',
      'Acute lymphoblastic leukemia',
      'ALL',
      'Hairy cell leukemia',
      'Waldenstrom macroglobulinemia',
      'Carcinoid tumor',
      'Neuroendocrine tumor',
      'Gastrointestinal stromal tumor',
      'GIST',
      'Kaposi sarcoma',
      'Merkel cell carcinoma',
      'Retinoblastoma',
      'Wilms tumor',
      'Neuroblastoma',
      'Rhabdomyosarcoma',
      'Ewing sarcoma',
      'Osteosarcoma',
      'Chondrosarcoma',
      'Chordoma',
      'Glioma',
      'Astrocytoma',
      'Glioblastoma',
      'Oligodendroglioma',
      'Ependymoma',
      'Meningioma',
      'Schwannoma',
      'Craniopharyngioma',
      'Pituitary adenoma',
      'Pineal tumor',
      'Medulloblastoma',
      'Germ cell tumor',
      'Teratoma',
      'Seminoma',
      'Nonseminoma',
      'Yolk sac tumor',
      'Choriocarcinoma',
      'Embryonal carcinoma',
      'Gestational trophoblastic disease',
      'Hydatidiform mole',
      'Invasive mole',
      'Choriocarcinoma',
      'Placental site trophoblastic tumor',
      'Epithelioid trophoblastic tumor',
      'Gynecologic cancers',
      'Endometrial cancer',
      'Fallopian tube cancer',
      'Primary peritoneal cancer',
      'Vulvar cancer',
      'Vaginal cancer',
      'Genitourinary cancers',
      'Penile cancer',
      'Urethral cancer',
      'Renal pelvis cancer',
      'Ureteral cancer',
      'Adrenocortical carcinoma',
      'Thymoma',
      'Thymic carcinoma',
      'Mesothelioma',
      'Anal cancer',
      'Small intestine cancer',
      'Gallbladder cancer',
      'Bile duct cancer',
      'Cholangiocarcinoma',
      'Primary liver cancer',
      'Hepatocellular carcinoma',
      'Intrahepatic cholangiocarcinoma',
      'Salivary gland cancer',
      'Nasal cavity cancer',
      'Paranasal sinus cancer',
      'Nasopharyngeal cancer',
      'Oropharyngeal cancer',
      'Hypopharyngeal cancer',
      'Laryngeal cancer',
      'Tracheal cancer',
      'Bronchial cancer',
      'Eye cancer',
      'Uveal melanoma',
      'Conjunctival melanoma',
      'Eyelid carcinoma',
      'Lacrimal gland tumor',
      'Orbital tumor',
      'Ear cancer',
      'Skin adnexal carcinoma',
      'Dermatofibrosarcoma protuberans',
      'Angiosarcoma',
      'Leiomyosarcoma',
      'Liposarcoma',
      'Malignant fibrous histiocytoma',
      'Synovial sarcoma',
      'Clear cell sarcoma',
      'Epithelioid sarcoma',
      'Alveolar soft part sarcoma',
      'Desmoplastic small round cell tumor',
      'PEComa',
      'Inflammatory myofibroblastic tumor',
      'Solitary fibrous tumor',
      'Hemangiopericytoma',
      'Giant cell tumor of bone',
      'Adamantinoma',
      'Hemangioendothelioma',
      'Langerhans cell histiocytosis',
      'Erdheim-Chester disease',
      'Rosai-Dorfman disease',
      'Castleman disease',
      'POEMS syndrome',
      'Paraneoplastic syndromes',
      'Tumor lysis syndrome',
      'Hypercalcemia of malignancy',
      'Syndrome of inappropriate antidiuretic hormone secretion',
      'SIADH',
      'Ectopic Cushing\'s syndrome',
      'Lambert-Eaton myasthenic syndrome',
      'Myasthenia gravis',
      'Paraneoplastic cerebellar degeneration',
      'Limbic encephalitis',
      'Anti-NMDA receptor encephalitis',
      'Opsoclonus-myoclonus syndrome',
      'Stiff-person syndrome',
      'Neuromyotonia',
      'Acquired ichthyosis',
      'Acanthosis nigricans',
      'Tripe palms',
      'Leser-Trelat sign',
      'Sweet\'s syndrome',
      'Pyoderma gangrenosum',
      'Erythema gyratum repens',
      'Necrolytic migratory erythema',
      'Dermatomyositis',
      'Trousseau\'s syndrome',
      'Disseminated intravascular coagulation',
      'DIC',
      'Thrombotic thrombocytopenic purpura',
      'TTP',
      'Hemolytic uremic syndrome',
      'HUS',
      'Cancer therapy',
      'Chemotherapy',
      'Radiation therapy',
      'Surgery',
      'Targeted therapy',
      'Immunotherapy',
      'Hormone therapy',
      'Stem cell transplant',
      'Bone marrow transplant',
      'CAR T-cell therapy',
      'Palliative care',
      'Hospice care',
      'Clinical trials',
      'Supportive care',
      'Survivorship',
      'Screening',
      'Prevention',
      'Genetics',
      'Genomics',
      'Precision medicine',
      'Personalized medicine',
      'Biomarkers',
      'Liquid biopsy',
      'Next-generation sequencing',
      'NGS',
      'Bioinformatics',
      'Epidemiology',
      'Public health',
      'Global health',
      'Health policy',
      'Health economics',
      'Medical ethics',
      'Medical education',
      'Research',
      'Evidence-based medicine',
      'EBM',
      'Quality improvement',
      'Patient safety',
      'Health literacy',
      'Telemedicine',
      'Digital health',
      'Artificial intelligence',
      'Machine learning',
      'Big data',
      'Wearable technology',
      'Electronic health records',
      'EHR',
      'Interoperability',
      'Privacy',
      'Security',
      'HIPAA',
      'GDPR',
      'Informed consent',
      'Clinical decision support',
      'Population health management',
      'Value-based care',
      'Accountable care organizations',
      'ACOs',
      'Patient-centered medical home',
      'PCMH',
      'Health disparities',
      'Social determinants of health',
      'Cultural competence',
      'Integrative medicine',
      'Complementary and alternative medicine',
      'CAM',
      'Mind-body medicine',
      'Acupuncture',
      'Chiropractic',
      'Naturopathy',
      'Homeopathy',
      'Herbal medicine',
      'Dietary supplements',
      'Vitamins',
      'Minerals',
      'Probiotics',
      'Medical cannabis',
      'Psychedelics',
      'Wellness',
      'Nutrition',
      'Exercise',
      'Sleep',
      'Stress management',
      'Mindfulness',
      'Yoga',
      'Meditation',
      'Tai chi',
      'Biofeedback',
      'Hypnosis',
      'Aromatherapy',
      'Massage therapy',
      'Reiki',
      'Therapeutic touch',
      'Music therapy',
      'Art therapy',
      'Pet therapy',
      'Nature therapy',
      'Forest bathing',
      'Spiritual care',
      'Chaplaincy',
      'Pastoral care',
      'End-of-life care',
      'Advance directives',
      'Living will',
      'Durable power of attorney for health care',
      'Do not resuscitate',
      'DNR',
      'Do not intubate',
      'DNI',
      'Physician orders for life-sustaining treatment',
      'POLST',
      'Medical orders for life-sustaining treatment',
      'MOLST',
      'Grief',
      'Bereavement',
      'Mourning',
      'Coping',
      'Resilience',
      'Hope',
      'Meaning',
      'Purpose',
      'Gratitude',
      'Forgiveness',
      'Compassion',
      'Empathy',
      'Altruism',
      'Volunteering',
      'Community',
      'Social support',
      'Relationships',
      'Family',
      'Friends',
      'Love',
      'Happiness',
      'Well-being',
      'Flourishing',
      'Self-care',
      'Self-compassion',
      'Self-esteem',
      'Self-efficacy',
      'Self-actualization',
      'Personal growth',
      'Lifelong learning',
      'Creativity',
      'Curiosity',
      'Humor',
      'Play',
      'Rest',
      'Relaxation',
      'Vacation',
      'Hobbies',
      'Interests',
      'Passions',
      'Flow',
      'Savoring',
      'Optimism',
      'Pessimism',
      'Realism',
      'Nihilism',
      'Existentialism',
      'Stoicism',
      'Epicureanism',
      'Utilitarianism',
      'Deontology',
      'Virtue ethics',
      'Feminist ethics',
      'Care ethics',
      'Narrative ethics',
      'Principlism',
      'Autonomy',
      'Beneficence',
      'Non-maleficence',
      'Justice',
      'Confidentiality',
      'Fidelity',
      'Veracity',
      'Paternalism',
      'Maternalism',
      'Professionalism',
      'Burnout',
      'Moral distress',
      'Moral injury',
      'Medical errors',
      'Adverse events',
      'Near misses',
      'Root cause analysis',
      'Failure mode and effects analysis',
      'FMEA',
      'Plan-Do-Study-Act',
      'PDSA',
      'Six Sigma',
      'Lean',
      'Kaizen',
      'Checklists',
      'Timeouts',
      'Huddles',
      'Debriefings',
      'Simulation',
      'Team training',
      'TeamSTEPPS',
      'Crew resource management',
      'CRM',
      'Just culture',
      'High-reliability organizations',
      'HROs',
      'Patient-reported outcomes',
      'PROs',
      'Patient-reported outcome measures',
      'PROMs',
      'Patient-reported experience measures',
      'PREMs',
      'Shared decision-making',
      'SDM',
      'Patient engagement',
      'Patient activation',
      'Patient empowerment',
      'Patient advocacy',
      'Patient navigation',
      'Peer support',
      'Support groups',
      'Online communities',
      'Social media',
      'Health information technology',
      'HIT',
      'Health informatics',
      'Clinical informatics',
      'Consumer health informatics',
      'Public health informatics',
      'Global health informatics',
      'Translational bioinformatics',
      'Clinical research informatics',
      'Data science',
      'Data analytics',
      'Predictive modeling',
      'Natural language processing',
      'NLP',
      'Computer vision',
      'Robotics',
      'Internet of Things',
      'IoT',
      'Blockchain',
      'Virtual reality',
      'VR',
      'Augmented reality',
      'AR',
      'Mixed reality',
      'MR',
      'Gamification',
      'Personalized learning',
      'Adaptive learning',
      'Competency-based education',
      'Interprofessional education',
      'IPE',
      'Continuing medical education',
      'CME',
      'Maintenance of certification',
      'MOC',
      'Professional development',
      'Mentorship',
      'Coaching',
      'Leadership',
      'Management',
      'Administration',
      'Finance',
      'Marketing',
      'Human resources',
      'Operations',
      'Strategy',
      'Innovation',
      'Entrepreneurship',
      'Startups',
      'Venture capital',
      'Private equity',
      'Mergers and acquisitions',
      'M&A',
      'Regulation',
      'Compliance',
      'Law',
      'Policy',
      'Advocacy',
      'Lobbying',
      'Politics',
      'Government',
      'Non-governmental organizations',
      'NGOs',
      'Foundations',
      'Philanthropy',
      'Social enterprise',
      'Corporate social responsibility',
      'CSR',
      'Global citizenship',
      'Sustainable development goals',
      'SDGs',
      'Universal health coverage',
      'UHC',
      'Primary health care',
      'PHC',
      'Health systems strengthening',
      'HSS',
      'Health workforce',
      'Health financing',
      'Health information systems',
      'HIS',
      'Service delivery',
      'Medical products',
      'Vaccines',
      'Technologies',
      'Leadership and governance',
      'Monitoring and evaluation',
      'M&E',
      'Impact assessment',
      'Cost-effectiveness analysis',
      'Cost-benefit analysis',
      'Budget impact analysis',
      'Health technology assessment',
      'HTA',
      'Comparative effectiveness research',
      'CER',
      'Patient-centered outcomes research',
      'PCOR',
      'Implementation science',
      'Dissemination and implementation',
      'D&I',
      'Knowledge translation',
      'KT',
      'Scale-up',
      'Sustainability',
      'Capacity building',
      'Technical assistance',
      'Partnerships',
      'Collaboration',
      'Coordination',
      'Communication',
      'Networking',
      'Community engagement',
      'Stakeholder engagement',
      'User-centered design',
      'Human-centered design',
      'Design thinking',
      'Agile',
      'Scrum',
      'Kanban',
      'Lean startup',
      'Business model canvas',
      'Value proposition canvas',
      'SWOT analysis',
      'PESTEL analysis',
      'Porter\'s five forces',
      'BCG matrix',
      'Ansoff matrix',
      'Balanced scorecard',
      'Key performance indicators',
      'KPIs',
      'Objectives and key results',
      'OKRs',
      'SMART goals',
      'GROW model',
      'STAR method',
      'Elevator pitch',
      'Presentation skills',
      'Public speaking',
      'Writing skills',
      'Negotiation skills',
      'Conflict resolution',
      'Emotional intelligence',
      'EQ',
      'Social intelligence',
      'Cultural intelligence',
      'CQ',
      'Adaptability',
      'Resilience',
      'Grit',
      'Growth mindset',
      'Fixed mindset',
      'Bias',
      'Unconscious bias',
      'Stereotypes',
      'Prejudice',
      'Discrimination',
      'Diversity',
      'Equity',
      'Inclusion',
      'Belonging',
      'Allyship',
      'Microaggressions',
      'Privilege',
      'Intersectionality',
      'Social justice',
      'Human rights',
      'Health equity',
      'Health disparities',
      'Health for all',
      'One Health',
      'Planetary health',
      'Climate change',
      'Air pollution',
      'Water pollution',
      'Soil pollution',
      'Noise pollution',
      'Light pollution',
      'Plastic pollution',
      'Deforestation',
      'Biodiversity loss',
      'Ecosystem services',
      'Circular economy',
      'Green chemistry',
      'Sustainable agriculture',
      'Renewable energy',
      'Energy efficiency',
      'Waste management',
      'Recycling',
      'Composting',
      'Water conservation',
      'Environmental justice',
      'Disaster preparedness',
      'Emergency response',
      'Humanitarian aid',
      'Refugee health',
      'Migrant health',
      'Global security',
      'Bioterrorism',
      'Pandemic preparedness',
      'Antimicrobial resistance',
      'AMR',
      'One Health approach to AMR',
      'Neglected tropical diseases',
      'NTDs',
      'Rare diseases',
      'Orphan drugs',
      'Personalized nutrition',
      'Nutrigenomics',
      'Metabolomics',
      'Proteomics',
      'Genomics',
      'Epigenomics',
      'Transcriptomics',
      'Microbiome',
      'Gut-brain axis',
      'Immunome',
      'Connectome',
      'Exposome',
      'Phenome',
      'Systems biology',
      'Network medicine',
      'Computational biology',
      'Bioinformatics',
      'Biostatistics',
      'Epidemiology',
      'Clinical trials',
      'Randomized controlled trials',
      'RCTs',
      'Observational studies',
      'Cohort studies',
      'Case-control studies',
      'Cross-sectional studies',
      'Ecological studies',
      'Systematic reviews',
      'Meta-analyses',
      'Qualitative research',
      'Mixed methods research',
      'Survey research',
      'Delphi method',
      'Nominal group technique',
      'Focus groups',
      'Interviews',
      'Case studies',
      'Ethnography',
      'Grounded theory',
      'Phenomenology',
      'Action research',
      'Participatory research',
      'Community-based participatory research',
      'CBPR',
      'Patient and public involvement',
      'PPI',
      'Research ethics',
      'Institutional review board',
      'IRB',
      'Data and safety monitoring board',
      'DSMB',
      'Conflict of interest',
      'COI',
      'Research misconduct',
      'Fabrication',
      'Falsification',
      'Plagiarism',
      'Authorship',
      'Peer review',
      'Open science',
      'Open access',
      'Open data',
      'FAIR principles',
      'Reproducibility',
      'Replicability',
      'Generalizability',
      'Validity',
      'Reliability',
      'Bias',
      'Confounding',
      'Effect modification',
      'Causality',
      'Hill\'s criteria',
      'Counterfactuals',
      'Propensity scores',
      'Instrumental variables',
      'Regression discontinuity',
      'Difference-in-differences',
      'Statistical significance',
      'P-value',
      'Confidence interval',
      'Effect size',
      'Power',
      'Sample size',
      'Bayesian statistics',
      'Frequentist statistics',
      'Machine learning',
      'Supervised learning',
      'Unsupervised learning',
      'Reinforcement learning',
      'Deep learning',
      'Neural networks',
      'Convolutional neural networks',
      'CNNs',
      'Recurrent neural networks',
      'RNNs',
      'Long short-term memory',
      'LSTM',
      'Transformers',
      'Generative adversarial networks',
      'GANs',
      'Decision trees',
      'Random forests',
      'Support vector machines',
      'SVMs',
      'K-nearest neighbors',
      'KNN',
      'K-means clustering',
      'Hierarchical clustering',
      'Principal component analysis',
      'PCA',
      'T-distributed stochastic neighbor embedding',
      't-SNE',
      'Uniform manifold approximation and projection',
      'UMAP',
      'Feature engineering',
      'Model selection',
      'Hyperparameter tuning',
      'Cross-validation',
      'Regularization',
      'Overfitting',
      'Underfitting',
      'Bias-variance tradeoff',
      'Interpretability',
      'Explainability',
      'SHAP',
      'LIME',
      'Fairness',
      'Accountability',
      'Transparency',
      'Ethics of AI',
      'AI safety',
      'AI alignment',
      'Singularity',
      'Transhumanism',
      'Posthumanism',
      'Cyborgs',
      'Androids',
      'Robots',
      'Drones',
      'Self-driving cars',
      'Smart homes',
      'Smart cities',
      'Internet of Bodies',
      'IoB',
      'Brain-computer interfaces',
      'BCIs',
      'Neurotechnology',
      'Neuroethics',
      'Genethics',
      'Cloning',
      'Gene editing',
      'CRISPR',
      'Synthetic biology',
      'Artificial life',
      'Nanotechnology',
      'Quantum computing',
      'Space exploration',
      'Astrobiology',
      'SETI',
      'Fermi paradox',
      'Drake equation',
      'Cosmology',
      'Astrophysics',
      'Particle physics',
      'String theory',
      'M-theory',
      'Loop quantum gravity',
      'Holographic principle',
      'Multiverse',
      'Anthropic principle',
      'Philosophy of science',
      'Epistemology',
      'Metaphysics',
      'Ontology',
      'Logic',
      'Ethics',
      'Aesthetics',
      'Political philosophy',
      'Philosophy of mind',
      'Philosophy of language',
      'Philosophy of religion',
      'History of philosophy',
      'Ancient philosophy',
      'Medieval philosophy',
      'Modern philosophy',
      'Contemporary philosophy',
      'Analytic philosophy',
      'Continental philosophy',
      'Eastern philosophy',
      'Western philosophy',
      'African philosophy',
      'Latin American philosophy',
      'Indigenous philosophy',
      'Feminist philosophy',
      'Queer theory',
      'Critical race theory',
      'Postcolonialism',
      'Postmodernism',
      'Post-structuralism',
      'Structuralism',
      'Phenomenology',
      'Existentialism',
      'Pragmatism',
      'Logical positivism',
      'Empiricism',
      'Rationalism',
      'Idealism',
      'Materialism',
      'Dualism',
      'Monism',
      'Pluralism',
      'Nihilism',
      'Absurdism',
      'Humanism',
      'Secularism',
      'Atheism',
      'Agnosticism',
      'Theism',
      'Deism',
      'Pantheism',
      'Panentheism',
      'Polytheism',
      'Monotheism',
      'Henotheism',
      'Kathenotheism',
      'Animism',
      'Shamanism',
      'Paganism',
      'Wicca',
      'Druidry',
      'Asatru',
      'Hellenism',
      'Kemeticism',
      'Rodnovery',
      'Zoroastrianism',
      'Judaism',
      'Christianity',
      'Islam',
      'Baha\'i Faith',
      'Sikhism',
      'Hinduism',
      'Buddhism',
      'Jainism',
      'Taoism',
      'Confucianism',
      'Shinto',
      'New religious movements',
      'Scientology',
      'Raëlism',
      'Thelema',
      'Satanism',
      'Discordianism',
      'Pastafarianism',
      'Jediism',
      'Mythology',
      'Folklore',
      'Legends',
      'Fairy tales',
      'Fables',
      'Epics',
      'Poetry',
      'Prose',
      'Fiction',
      'Non-fiction',
      'Drama',
      'Comedy',
      'Tragedy',
      'Satire',
      'Irony',
      'Parody',
      'Allegory',
      'Symbolism',
      'Metaphor',
      'Simile',
      'Personification',
      'Hyperbole',
      'Understatement',
      'Alliteration',
      'Assonance',
      'Consonance',
      'Onomatopoeia',
      'Rhyme',
      'Rhythm',
      'Meter',
      'Stanza',
      'Sonnet',
      'Haiku',
      'Limerick',
      'Villanelle',
      'Sestina',
      'Ode',
      'Elegy',
      'Ballad',
      'Epic poem',
      'Narrative poem',
      'Lyric poem',
      'Dramatic poem',
      'Novel',
      'Short story',
      'Novella',
      'Play',
      'Screenplay',
      'Essay',
      'Biography',
      'Autobiography',
      'Memoir',
      'Journal',
      'Diary',
      'Letter',
      'Speech',
      'Sermon',
      'Manifesto',
      'Treatise',
      'Critique',
      'Review',
      'Report',
      'Article',
      'Blog post',
      'Tweet',
      'Meme',
      'Graphic novel',
      'Comic book',
      'Manga',
      'Webcomic',
      'Visual arts',
      'Painting',
      'Drawing',
      'Sculpture',
      'Printmaking',
      'Photography',
      'Filmmaking',
      'Animation',
      'Video art',
      'Installation art',
      'Performance art',
      'Conceptual art',
      'Land art',
      'Street art',
      'Graffiti',
      'Architecture',
      'Design',
      'Graphic design',
      'Industrial design',
      'Fashion design',
      'Interior design',
      'Web design',
      'User interface design',
      'UI',
      'User experience design',
      'UX',
      'Game design',
      'Sound design',
      'Music',
      'Classical music',
      'Baroque',
      'Classical',
      'Romantic',
      'Modern',
      'Contemporary',
      'Opera',
      'Symphony',
      'Concerto',
      'Sonata',
      'Chamber music',
      'Choral music',
      'Jazz',
      'Blues',
      'Ragtime',
      'Swing',
      'Bebop',
      'Cool jazz',
      'Hard bop',
      'Modal jazz',
      'Free jazz',
      'Fusion',
      'Smooth jazz',
      'Folk music',
      'Country music',
      'Bluegrass',
      'Gospel',
      'Rhythm and blues',
      'R&B',
      'Soul',
      'Funk',
      'Disco',
      'Rock and roll',
      'Rock',
      'Psychedelic rock',
      'Progressive rock',
      'Hard rock',
      'Heavy metal',
      'Punk rock',
      'New wave',
      'Alternative rock',
      'Indie rock',
      'Grunge',
      'Britpop',
      'Pop music',
      'Hip hop',
      'Rap',
      'Electronic music',
      'Ambient',
      'Techno',
      'House',
      'Trance',
      'Drum and bass',
      'Dubstep',
      'EDM',
      'World music',
      'Reggae',
      'Salsa',
      'Flamenco',
      'Tango',
      'Bollywood',
      'K-pop',
      'J-pop',
      'C-pop',
      'Latin music',
      'African music',
      'Celtic music',
      'Middle Eastern music',
      'Caribbean music',
      'Performing arts',
      'Theater',
      'Dance',
      'Ballet',
      'Modern dance',
      'Contemporary dance',
      'Tap dance',
      'Jazz dance',
      'Hip hop dance',
      'Folk dance',
      'Ballroom dance',
      'Circus',
      'Magic',
      'Puppetry',
      'Mime',
      'Stand-up comedy',
      'Improvisational theater',
      'Musical theater',
      'Vaudeville',
      'Burlesque',
      'Cabaret',
      'Drag',
      'History',
      'Prehistory',
      'Ancient history',
      'Middle Ages',
      'Renaissance',
      'Age of Discovery',
      'Reformation',
      'Scientific Revolution',
      'Enlightenment',
      'Industrial Revolution',
      'American Revolution',
      'French Revolution',
      'Napoleonic Wars',
      'Victorian era',
      'World War I',
      'Interwar period',
      'World War II',
      'Cold War',
      'Post-Cold War era',
      'Contemporary history',
      'Historiography',
      'Archaeology',
      'Anthropology',
      'Sociology',
      'Psychology',
      'Economics',
      'Political science',
      'Geography',
      'Linguistics',
      'Law',
      'Education',
      'Library science',
      'Museum studies',
      'Archival science',
      'Cultural studies',
      'Gender studies',
      'Race and ethnic studies',
      'Area studies',
      'African studies',
      'American studies',
      'Asian studies',
      'European studies',
      'Latin American studies',
      'Middle Eastern studies',
      'Russian and East European studies',
      'Business',
      'Management',
      'Finance',
      'Accounting',
      'Marketing',
      'Human resources',
      'Operations management',
      'Supply chain management',
      'Logistics',
      'International business',
      'Entrepreneurship',
      'Nonprofit management',
      'Public administration',
      'Hospitality management',
      'Sports management',
      'Health care administration',
      'Engineering',
      'Civil engineering',
      'Mechanical engineering',
      'Electrical engineering',
      'Chemical engineering',
      'Aerospace engineering',
      'Biomedical engineering',
      'Computer engineering',
      'Software engineering',
      'Materials science',
      'Nuclear engineering',
      'Environmental engineering',
      'Industrial engineering',
      'Systems engineering',
      'Agricultural engineering',
      'Mining engineering',
      'Petroleum engineering',
      'Geological engineering',
      'Naval architecture',
      'Marine engineering',
      'Ocean engineering',
      'Mathematics',
      'Arithmetic',
      'Algebra',
      'Geometry',
      'Trigonometry',
      'Calculus',
      'Statistics',
      'Probability',
      'Logic',
      'Number theory',
      'Graph theory',
      'Topology',
      'Differential equations',
      'Linear algebra',
      'Abstract algebra',
      'Real analysis',
      'Complex analysis',
      'Numerical analysis',
      'Game theory',
      'Optimization',
      'Cryptography',
      'Information theory',
      'Computer science',
      'Algorithms',
      'Data structures',
      'Programming languages',
      'Operating systems',
      'Computer networks',
      'Databases',
      'Artificial intelligence',
      'Computer graphics',
      'Human-computer interaction',
      'HCI',
      'Software engineering',
      'Theory of computation',
      'Cybersecurity',
      'Natural sciences',
      'Physics',
      'Classical mechanics',
      'Thermodynamics',
      'Electromagnetism',
      'Relativity',
      'Quantum mechanics',
      'Particle physics',
      'Nuclear physics',
      'Atomic physics',
      'Molecular physics',
      'Optical physics',
      'Condensed matter physics',
      'Astrophysics',
      'Cosmology',
      'Biophysics',
      'Geophysics',
      'Chemistry',
      'Organic chemistry',
      'Inorganic chemistry',
      'Physical chemistry',
      'Analytical chemistry',
      'Biochemistry',
      'Geochemistry',
      'Astrochemistry',
      'Nuclear chemistry',
      'Polymer chemistry',
      'Materials chemistry',
      'Environmental chemistry',
      'Theoretical chemistry',
      'Computational chemistry',
      'Medicinal chemistry',
      'Supramolecular chemistry',
      'Green chemistry',
      'Food chemistry',
      'Forensic chemistry',
      'Biology',
      'Cell biology',
      'Molecular biology',
      'Genetics',
      'Evolution',
      'Ecology',
      'Botany',
      'Zoology',
      'Microbiology',
      'Immunology',
      'Neuroscience',
      'Physiology',
      'Anatomy',
      'Histology',
      'Embryology',
      'Developmental biology',
      'Paleontology',
      'Marine biology',
      'Conservation biology',
      'Systems biology',
      'Synthetic biology',
      'Astrobiology',
      'Earth sciences',
      'Geology',
      'Geophysics',
      'Geochemistry',
      'Oceanography',
      'Meteorology',
      'Climatology',
      'Hydrology',
      'Glaciology',
      'Paleoclimatology',
      'Volcanology',
      'Seismology',
      'Tectonics',
      'Mineralogy',
      'Petrology',
      'Sedimentology',
      'Stratigraphy',
      'Geomorphology',
      'Pedology',
      'Edaphology',
      'Limnology',
      'Ecology',
      'Environmental science',
      'Space sciences',
      'Astronomy',
      'Astrophysics',
      'Cosmology',
      'Planetary science',
      'Astrobiology',
      'Formal sciences',
      'Logic',
      'Mathematics',
      'Statistics',
      'Computer science',
      'Systems science',
      'Decision theory',
      'Game theory',
      'Information theory',
      'Cybernetics',
      'Control theory',
      'Operations research',
      'Applied sciences',
      'Agriculture',
      'Architecture',
      'Design',
      'Education',
      'Engineering',
      'Forensics',
      'Health sciences',
      'Journalism',
      'Law',
      'Library science',
      'Management',
      'Medicine',
      'Military science',
      'Public administration',
      'Social work',
      'Transportation',
      'Urban planning',
      'Recreation',
      'Tourism',
      'Sports',
      'Hobbies',
      'Crafts',
      'Gardening',
      'Cooking',
      'Baking',
      'Knitting',
      'Sewing',
      'Woodworking',
      'Metalworking',
      'Pottery',
      'Calligraphy',
      'Origami',
      'Scrapbooking',
      'Stamping',
      'Jewelry making',
      'Candle making',
      'Soap making',
      'Flower arranging',
      'Model building',
      'Coin collecting',
      'Stamp collecting',
      'Antiquing',
      'Genealogy',
      'Birdwatching',
      'Stargazing',
      'Hiking',
      'Camping',
      'Backpacking',
      'Fishing',
      'Hunting',
      'Boating',
      'Sailing',
      'Kayaking',
      'Canoeing',
      'Rafting',
      'Surfing',
      'Windsurfing',
      'Kitesurfing',
      'Waterskiing',
      'Wakeboarding',
      'Scuba diving',
      'Snorkeling',
      'Freediving',
      'Swimming',
      'Diving',
      'Water polo',
      'Synchronized swimming',
      'Rowing',
      'Canoe polo',
      'Dragon boat',
      'Sledding',
      'Skiing',
      'Snowboarding',
      'Cross-country skiing',
      'Ski jumping',
      'Freestyle skiing',
      'Alpine skiing',
      'Biathlon',
      'Luge',
      'Skeleton',
      'Bobsleigh',
      'Curling',
      'Ice hockey',
      'Figure skating',
      'Speed skating',
      'Short track speed skating',
      'Bandy',
      'Ringette',
      'Broomball',
      'Floorball',
      'Roller hockey',
      'Inline hockey',
      'Skateboarding',
      'Roller skating',
      'Inline skating',
      'Aggressive inline skating',
      'Scootering',
      'BMX',
      'Cycling',
      'Road cycling',
      'Track cycling',
      'Mountain biking',
      'Cyclo-cross',
      'Cycle speedway',
      'Artistic cycling',
      'Cycle polo',
      'Unicycling',
      'Motorcycling',
      'Road racing',
      'Motocross',
      'Enduro',
      'Supermoto',
      'Trial',
      'Freestyle motocross',
      'Track racing',
      'Speedway',
      'Grasstrack',
      'Ice speedway',
      'Auto racing',
      'Formula racing',
      'Sports car racing',
      'Touring car racing',
      'Stock car racing',
      'Rallying',
      'Off-road racing',
      'Drag racing',
      'Kart racing',
      'Drifting',
      'Hillclimbing',
      'Rallycross',
      'Autocross',
      'Autograss',
      'Banger racing',
      'Demolition derby',
      'Folkrace',
      'Legends car racing',
      'Midget car racing',
      'Sprint car racing',
      'Truck racing',
      'Motorcycle drag racing',
      'Motorcycle speedway',
      'Motorcycle trials',
      'Sidecarcross',
      'ATV racing',
      'Snowmobile racing',
      'Powerboat racing',
      'Air racing',
      'Drone racing',
      'Equestrianism',
      'Dressage',
      'Show jumping',
      'Eventing',
      'Endurance riding',
      'Reining',
      'Vaulting',
      'Horse racing',
      'Harness racing',
      'Polo',
      'Polocrosse',
      'Tent pegging',
      'Rodeo',
      'Bull riding',
      'Saddle bronc riding',
      'Bareback bronc riding',
      'Steer wrestling',
      'Team roping',
      'Tie-down roping',
      'Barrel racing',
      'Goat tying',
      'Breakaway roping',
      'Pole bending',
      'Archery',
      'Shooting',
      'Fencing',
      'Modern pentathlon',
      'Biathlon',
      'Triathlon',
      'Duathlon',
      'Aquathlon',
      'Aquabike',
      'Quadrathlon',
      'Pentathlon',
      'Heptathlon',
      'Decathlon',
      'Athletics',
      'Running',
      'Sprinting',
      'Middle-distance running',
      'Long-distance running',
      'Marathon',
      'Ultramarathon',
      'Hurdles',
      'Steeplechase',
      'Relay race',
      'Racewalking',
      'Jumping',
      'High jump',
      'Pole vault',
      'Long jump',
      'Triple jump',
      'Throwing',
      'Shot put',
      'Discus throw',
      'Javelin throw',
      'Hammer throw',
      'Weight throw',
      'Combined events',
      'Gymnastics',
      'Artistic gymnastics',
      'Rhythmic gymnastics',
      'Trampoline gymnastics',
      'Tumbling',
      'Acrobatic gymnastics',
      'Aerobic gymnastics',
      'Parkour',
      'Freerunning',
      'Weightlifting',
      'Powerlifting',
      'Strongman',
      'Bodybuilding',
      'CrossFit',
      'Wrestling',
      'Greco-Roman wrestling',
      'Freestyle wrestling',
      'Folkstyle wrestling',
      'Sumo',
      'Sambo',
      'Judo',
      'Brazilian jiu-jitsu',
      'Jujutsu',
      'Aikido',
      'Karate',
      'Taekwondo',
      'Kung fu',
      'Wushu',
      'Muay Thai',
      'Kickboxing',
      'Boxing',
      'Savate',
      'Lethwei',
      'Sanshou',
      'Capoeira',
      'Krav Maga',
      'Mixed martial arts',
      'MMA',
      'Fencing',
      'Kendo',
      'Iaido',
      'Jodo',
      'Naginatajutsu',
      'Sojutsu',
      'Kyudo',
      'Yabusame',
      'Bajutsu',
      'Hojojutsu',
      'Ninjutsu',
      'Bujinkan',
      'Genbukan',
      'Jinenkan',
      'Togakure-ryu',
      'Kukishin-ryu',
      'Gyokko-ryu',
      'Koto-ryu',
      'Shinden Fudo-ryu',
      'Takagi Yoshin-ryu',
      'Gikan-ryu',
      'Gyokushin-ryu',
      'Kumogakure-ryu',
      'Team sports',
      'Association football',
      'Soccer',
      'American football',
      'Canadian football',
      'Arena football',
      'Flag football',
      'Rugby football',
      'Rugby league',
      'Rugby union',
      'Rugby sevens',
      'Touch rugby',
      'Australian rules football',
      'Gaelic football',
      'International rules football',
      'Baseball',
      'Softball',
      'Cricket',
      'Test cricket',
      'One Day International',
      'Twenty20',
      'The Hundred',
      'Basketball',
      '3x3 basketball',
      'Netball',
      'Volleyball',
      'Beach volleyball',
      'Handball',
      'Beach handball',
      'Field hockey',
      'Ice hockey',
      'Bandy',
      'Lacrosse',
      'Box lacrosse',
      'Field lacrosse',
      'Women\'s lacrosse',
      'Intercrosse',
      'Polo',
      'Water polo',
      'Canoe polo',
      'Cycle polo',
      'Elephant polo',
      'Yak polo',
      'Segway polo',
      'Ultimate',
      'Frisbee',
      'Dodgeball',
      'Kickball',
      'Quidditch',
      'Korfball',
      'Fistball',
      'Tchoukball',
      'Sepak takraw',
      'Bossaball',
      'Footvolley',
      'Goalball',
      'Torball',
      'Wheelchair basketball',
      'Wheelchair rugby',
      'Wheelchair tennis',
      'Para-ice hockey',
      'Sled hockey',
      'Boccia',
      'CP football',
      'IBSA blind football',
      'Paralympic volleyball',
      'Sitting volleyball',
      'Wheelchair curling',
      'Wheelchair dance sport',
      'Para-athletics',
      'Para-swimming',
      'Para-cycling',
      'Para-equestrian',
      'Para-powerlifting',
      'Para-table tennis',
      'Para-archery',
      'Para-shooting',
      'Para-judo',
      'Para-taekwondo',
      'Para-badminton',
      'Para-canoe',
      'Para-rowing',
      'Para-triathlon',
      'Para-snowboard',
      'Para-alpine skiing',
      'Para-Nordic skiing',
      'Para-biathlon',
      'Para-ice hockey',
      'Mind sports',
      'Chess',
      'Go',
      'Shogi',
      'Xiangqi',
      'Checkers',
      'Draughts',
      'Reversi',
      'Othello',
      'Backgammon',
      'Mahjong',
      'Dominoes',
      'Bridge',
      'Poker',
      'Scrabble',
      'Boggle',
      'Crossword puzzles',
      'Sudoku',
      'Kakuro',
      'KenKen',
      'Logic puzzles',
      'Mechanical puzzles',
      'Rubik\'s Cube',
      'Jigsaw puzzles',
      'Word searches',
      'Trivia',
      'Quizzes',
      'Board games',
      'Monopoly',
      'Catan',
      'Ticket to Ride',
      'Carcassonne',
      'Pandemic',
      'Risk',
      'Clue',
      'Battleship',
      'Stratego',
      'Axis & Allies',
      'Diplomacy',
      'Twilight Imperium',
      'Gloomhaven',
      'Dungeons & Dragons',
      'Pathfinder',
      'Warhammer',
      'Magic: The Gathering',
      'Pokémon Trading Card Game',
      'Yu-Gi-Oh!',
      'Hearthstone',
      'Gwent',
      'Legends of Runeterra',
      'Video games',
      'Action',
      'Adventure',
      'Role-playing',
      'RPG',
      'Strategy',
      'Simulation',
      'Sports',
      'Racing',
      'Fighting',
      'Puzzle',
      'Platformer',
      'Shooter',
      'First-person shooter',
      'FPS',
      'Third-person shooter',
      'TPS',
      'Stealth',
      'Survival',
      'Horror',
      'Rhythm',
      'Party',
      'Educational',
      'Exergame',
      'Casual',
      'Hypercasual',
      'Mobile',
      'PC',
      'Console',
      'Arcade',
      'MMORPG',
      'MOBA',
      'Battle royale',
      'Sandbox',
      'Open world',
      'Roguelike',
      'Metroidvania',
      'Visual novel',
      'Interactive fiction',
      'Text adventure',
      'Alternate reality game',
      'ARG',
      'Pervasive game',
      'Live action role-playing game',
      'LARP',
      'Tabletop role-playing game',
      'TRPG',
      'Wargame',
      'Miniature wargaming',
      'Card game',
      'Dice game',
      'Tile-based game',
      'Pen-and-paper game',
      'Party game',
      'Drinking game',
      'Children\'s game',
      'Singing game',
      'Street game',
      'Tag',
      'Hide-and-seek',
      'Red light, green light',
      'Hopscotch',
      'Marbles',
      'Jacks',
      'Cat\'s cradle',
      'Rock-paper-scissors',
      'Thumb war',
      'Pat-a-cake',
      'Duck, duck, goose',
      'Musical chairs',
      'Simon says',
      'Telephone',
      'Charades',
      'Pictionary',
      'Hangman',
      'Tic-tac-toe',
      'Dots and boxes',
      'Connect Four',
      'Guess Who?',
      'Operation',
      'Mouse Trap',
      'Twister',
      'Jenga',
      'Lego',
      'Play-Doh',
      'Crayons',
      'Coloring book',
      'Stickers',
      'Dolls',
      'Action figures',
      'Stuffed animals',
      'Toy cars',
      'Trains',
      'Planes',
      'Boats',
      'Robots',
      'Puzzles',
      'Kites',
      'Yo-yos',
      'Frisbees',
      'Balls',
      'Balloons',
      'Bubbles',
      'Swings',
      'Slides',
      'Seesaws',
      'Merry-go-rounds',
      'Jungle gyms',
      'Sandboxes',
      'Playhouses',
      'Treehouses',
      'Forts',
      'Blanket forts',
      'Pillow fights',
      'Tickling',
      'Piggyback rides',
      'Storytelling',
      'Reading',
      'Writing',
      'Drawing',
      'Painting',
      'Singing',
      'Dancing',
      'Acting',
      'Pretending',
      'Imagining',
      'Dreaming',
      'Sleeping',
      'Waking',
      'Eating',
      'Drinking',
      'Breathing',
      'Living',
      'Dying',
      'Beginning',
      'Ending',
      'Everything',
      'Nothing',
      'Something',
      'Anything',
      'Everything in between',
    ];
    Batch batch = db.batch();
    for (String name in initialMedicines) {
      batch.insert('medicines', {'name': name});
    }
    await batch.commit(noResult: true);
  }

  Future<List<Medicine>> searchMedicines(String query) async {
    final db = await database;
    if (query.isEmpty) {
      return [];
    }
    final List<Map<String, dynamic>> maps = await db.query(
      'medicines',
      where: 'name LIKE ?',
      whereArgs: ['$query%'],
      limit: 5,
    );
    return List.generate(maps.length, (i) {
      return Medicine.fromMap(maps[i]);
    });
  }
}
